# Generated by Django 5.1.3 on 2024-12-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutrition_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
