# Generated by Django 5.1.3 on 2024-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recipe_nutrition_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='nutrition_info',
            field=models.JSONField(default=dict, blank=True, null=True),
        ),
    ]
